## 其他创建numpy.array的方法

In [1]:
import numpy as np

## 特殊矩阵的创建 zeros方法ones方法full方法

> 利用zeros方法创建零数组，类型默认是float类型,第一个参数是数组的大小

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10).dtype

dtype('float64')

> 传入dtype参数，改成整数型

In [4]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

> 也给shape传入一个元组，获得的零矩阵就是一个二维数组

In [5]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.zeros(shape=(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

> 全为1矩阵的创建

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

> 利用full方法创建指定值的矩阵

In [8]:
np.full(shape=(3,5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## arange方法生成等步长数组 前闭后开

In [9]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

> 同理，在numpy中也有相似的arange方法生成前闭后开的数列,而且可以传入浮点数

In [10]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.arange(0, 2, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

## linspace方法生成指定点的数组 前闭后闭

In [12]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## random模块 生成随机数组 
## randomint方法seed方法random方法normal方法

> randomint方法生成一个数、一维数组和二维数组

In [13]:
np.random.randint(0, 10)

8

In [16]:
np.random.randint(0, 10, size = 10)

array([3, 1, 8, 1, 6, 0, 8, 7, 4, 9])

In [17]:
np.random.randint(0, 10, size = (3, 5))

array([[7, 3, 4, 2, 0],
       [0, 8, 1, 2, 0],
       [9, 5, 0, 3, 6]])

> 但是random方法是前闭后开类型的，无法取到后面一个数

In [15]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

> 随机种子的使用，如果随机种子的值相同，则两次随机数则也相同,可用于调试

In [19]:
np.random.seed(666)
np.random.randint(0,10,10)

array([2, 6, 9, 4, 3, 1, 0, 8, 7, 5])

In [20]:
np.random.seed(666)
np.random.randint(0,10,10)

array([2, 6, 9, 4, 3, 1, 0, 8, 7, 5])

> random模块下的random方法生成**0到1之间的浮点数**

In [22]:
np.random.random( 10)

array([0.192892  , 0.70084475, 0.29322811, 0.77447945, 0.00510884,
       0.11285765, 0.11095367, 0.24766823, 0.0232363 , 0.72732115])

> normal方法生成符合正态分布的浮点数, 可以指定均值与方差

In [23]:
np.random.normal()

-1.0887929860091878

In [24]:
np.random.normal(10,100)

-47.57707456697689

In [25]:
np.random.normal(10, 100, (3,5))

array([[-158.2900771 ,   32.91852477, -165.66252234,   94.46326187,
          37.72198634],
       [  95.2901533 ,   29.4599603 ,  141.06377157,  164.38436001,
         -42.90480243],
       [ -55.64722973,  -10.15057011,  -60.06158328,   78.71379544,
           7.39242436]])

>可以通过 ? 或是help 查询方法的使用

In [27]:
np.random.normal?

In [28]:
np.random?

In [30]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap