## 逻辑回归 新的超参数 阈值
> **阈值取不同的值，**

<img src='./picture/5-1.png'>
<img src='./picture/5-2.png'>
<img src='./picture/5-3.png'>
<img src='./picture/5-4.png'>

## 准确率和召回率的平衡
> **调用decision_function来**

In [2]:
import numpy as np
from sklearn import datasets
digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

import sys
sys.path.append('E:\github\ml_practice\ml_python')
from model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, seed = 666)

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train , y_train)
y_log_predict = log_reg.predict(X_test)

In [3]:
from sklearn.metrics import f1_score
f1_score(y_test, y_log_predict)

0.7999999999999999

In [4]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_log_predict)

array([[317,   6],
       [  8,  28]], dtype=int64)

## 实现不同的阈值

In [5]:
log_reg.decision_function(X_test)

array([-2.22290278e+01, -3.74633614e+01, -1.71949920e+01, -8.84056841e+01,
       -5.66671544e+01, -2.34575232e+01, -5.01115833e+01, -2.49394190e+01,
       -4.35553195e-01, -1.63245006e+01, -7.94611432e+01, -5.00142263e+01,
       -3.30443798e+01, -5.17366610e+01, -3.69415530e+01, -2.84035296e+01,
       -3.97994634e+01, -8.60232009e+01, -3.68935419e+01, -8.82643486e+00,
       -1.16461191e+01, -8.56335987e+01, -1.48383255e+01, -4.99104548e+01,
       -4.14505081e+00, -5.49506014e+01, -1.03120539e+01, -3.62479886e+01,
       -2.44983563e+01, -1.15682876e+01, -1.60389389e+01, -2.81523140e+01,
       -3.73832245e+01, -2.40550769e+01, -6.71193093e+00, -4.32129795e+00,
       -2.27161380e+01, -2.01586331e+01, -3.33185652e+01, -2.33800954e+01,
       -2.79350159e+01, -5.98428039e+01, -4.22644352e+01, -7.12080060e+01,
       -1.97193370e+01, -1.82993395e+01, -1.72025132e+01, -2.03340625e+01,
       -3.17180566e+01, -1.62318762e+01,  3.52743331e+00,  1.06166209e+01,
       -3.13767025e+01, -

In [6]:
log_reg.decision_function(X_test)[:10]

array([-22.22902776, -37.46336138, -17.19499203, -88.4056841 ,
       -56.66715437, -23.45752316, -50.11158332, -24.93941902,
        -0.4355532 , -16.32450065])

In [7]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
decision_scores = log_reg.decision_function(X_test)

In [9]:
y_predict_2 = np.array(decision_scores >= 5, dtype='int')

In [10]:
confusion_matrix(y_test, y_predict_2)

array([[323,   0],
       [ 16,  20]], dtype=int64)

In [11]:
y_predict_2 = np.array(decision_scores >= -5, dtype='int')

In [12]:
confusion_matrix(y_test, y_predict_2)

array([[308,  15],
       [  3,  33]], dtype=int64)