# 05 Numpy.array的基本操作

> ** 注意 这里建立了两个数组，使用了reshape方法将一维数组转化为二维数组**

In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## numpy基本属性

> **调用ndim方法查看数组的维数** 

> **调用shape方法查看大小，返回的是一个元组**

> **调用size方法查看元素的多少**

In [4]:
x.ndim

1

In [5]:
X.ndim

2

In [6]:
x.shape


(10,)

In [7]:
X.shape

(3, 5)

In [8]:
x.size

10

In [9]:
X.size

15

## numpy.array的数据访问

> **利用索引的方式----X[2][3]，但是使用切片时会产生问题**

> **为多维数组提供了更方便的访问方式---X[(2,3)]或是X[2,3]， 在[]中写入元组**

> **数组支持切片的方式访问，一维数组x[::2],其中第三个参数为步长**

> **多维数组也支持切片的方式访问---X[:2, :3], 二维数组的前两行与前三列**

> **多维数组的降维处理--X[1，:]、X[:，1]， 来取出一行或是一列**

> **<font color=red>切片的方法获取子矩阵，是以引用的方式获取的，修改子矩阵会对原矩阵有影响</font>**

> **<font color=red>调用copy方法可以复制原先的矩阵，修改时不会对原先的矩阵造成影响</font>**

---

In [10]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[0]

0

In [12]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
X[0]

array([0, 1, 2, 3, 4])

In [14]:
X[2][4]

14

In [15]:
X[(2,4)]

14

In [16]:
X[2,4]

14

---

In [17]:
x[0:5]

array([0, 1, 2, 3, 4])

In [18]:
x[::2]

array([0, 2, 4, 6, 8])

In [19]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [20]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

---

In [23]:
X[1,:]

array([5, 6, 7, 8, 9])

In [24]:
X[::, 1]

array([ 1,  6, 11])

In [25]:
X[:,0].ndim

1

---

In [28]:
subX = X[:2, :3]

In [29]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [32]:
subX[0,0] =100

In [33]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [34]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

---

In [37]:
subX2 = X[:2,:3].copy()
subX2

array([[100,   1,   2],
       [  5,   6,   7]])

In [38]:
subX2[0,0] =10000

In [39]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [40]:
subX2

array([[10000,     1,     2],
       [    5,     6,     7]])

## Reshape

> **reshape方法对数据的内容没有改变，只是对数组的维度改变**、

> **调用reshape方法没有对原数组改变,如果要得新数组，需要有新的引用**

> **reshape方法中传入参数-1， 目的是为了让计算机自动判断个数**

In [41]:
x.shape

(10,)

In [42]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> 调用reshape方法将一维向量转化为二维数组

In [48]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
x.ndim

1

In [52]:
B.ndim

2

> 传入参数-1，获得10行的数组或是10列的数组

In [53]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [54]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [55]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)