# 数组的合并与分割

In [1]:
import numpy  as np

In [8]:
x =  np.array([1 , 2, 3])
x

array([1, 2, 3])

In [9]:
y = np.array([3, 2, 1])
y

array([3, 2, 1])

## 数据合并

> **concatenate方法拼接，传入参数为一个列表，列表中存放要拼接的多个向量**

> **concatenate方法，axis参数表示拼接的方向,默认为0**

> **concatenate方法只能拼接相同维数的矩阵，不同维数的矩阵需要用到reshape方法**

> **vstack方法垂直方向将数据叠在一起，hstack方法同理,不需要reshape方法.**

In [10]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [13]:
np.concatenate([x, y , np.array([666, 666])])

array([  1,   2,   3,   3,   2,   1, 666, 666])

In [15]:
A = np.array([[1,3,2],[1,2,3]])
A

array([[1, 3, 2],
       [1, 2, 3]])

In [16]:
np.concatenate([A,A])

array([[1, 3, 2],
       [1, 2, 3],
       [1, 3, 2],
       [1, 2, 3]])

---
不同方向拼接矩阵

In [17]:
np.concatenate([A,A], axis=1)

array([[1, 3, 2, 1, 3, 2],
       [1, 2, 3, 1, 2, 3]])

---
拼接不同维数的矩阵

In [18]:
z = np.array([666,666,666])

In [19]:
z.ndim

1

In [20]:
np.concatenate([A,z])

ValueError: all the input arrays must have same number of dimensions

In [22]:
C = np.concatenate([A,z.reshape(1, -1)])

In [23]:
C

array([[  1,   3,   2],
       [  1,   2,   3],
       [666, 666, 666]])

In [24]:
A

array([[1, 3, 2],
       [1, 2, 3]])

---
vstack和hstack方法容错性更好,不需要维数相同

In [25]:
np.vstack([A,z])

array([[  1,   3,   2],
       [  1,   2,   3],
       [666, 666, 666]])

In [27]:
B = np.full((2,2), 100)
B

array([[100, 100],
       [100, 100]])

In [28]:
np.hstack([B,A])

array([[100, 100,   1,   3,   2],
       [100, 100,   1,   2,   3]])

## 数据分割

> **split方法分割数组,传入两个参数，第一个为要分割的数组，第二个为分割点的位置**

> **split方法也可以分割二维数组，第二个默认是行分割的位置，修改axis参数修改方向**

> **vsplit垂直方向上分割数组，hsplit水平方向上分割数组，避免修改axis参数**

In [29]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.split(x,(3,7))

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [34]:
x1,x2,x3 = np.split(x,(3,7))
print(x1,x2,x3)

[0 1 2] [3 4 5 6] [7 8 9]


In [36]:
A

array([[1, 3, 2],
       [1, 2, 3]])

---
二维数组的分割，行分割，列分割,***可以将特征向量和lable分割开成X，y***

In [46]:
A1,A2 = np.split(A,[1])

In [47]:
print(A1,A2)

[[1 3 2]] [[1 2 3]]


In [53]:
a1,a2 = np.split(A,[1],axis=1)
print(a1)
print("-"*10)
print(a2)

[[1]
 [1]]
----------
[[3 2]
 [2 3]]


In [54]:
np.vsplit(A,[1])

[array([[1, 3, 2]]), array([[1, 2, 3]])]

In [55]:
np.hsplit(A,[1])

[array([[1],
        [1]]), array([[3, 2],
        [2, 3]])]

> **利用hsplit方法和数组查询将矩阵分割成特征和label**

> **利用y[:,0]将y从二维数组变化成一维向量**

In [61]:
x,y  = np.hsplit(A,[-1])
print(x)
print(y)

[[1 3]
 [1 2]]
[[2]
 [3]]


In [62]:
y[:,0]

array([2, 3])