## numpy中的聚合操作

> **使用numpy中的sum函数比基础库中的sum函数效率高, 二维数组可以有参数axis**

> **使用numpy中的max函数和min函数求最大值和最小值**

> **prod方法求乘积，mean方法求平均值， median求中位数 percentile求百分位点**

> **var方法求方差,std方法求标准差**

In [2]:
import numpy as np
L = np.random.random(100)

In [3]:
L

array([0.670706  , 0.36233395, 0.28665409, 0.66103282, 0.13564092,
       0.34384539, 0.93190618, 0.07942389, 0.01826148, 0.60171099,
       0.70360963, 0.09458878, 0.89422576, 0.26599998, 0.51110659,
       0.49539476, 0.48127168, 0.39436515, 0.6886508 , 0.53712058,
       0.71775856, 0.18492601, 0.12074116, 0.96547411, 0.17827009,
       0.47119954, 0.98011295, 0.59298827, 0.5485332 , 0.71577893,
       0.0940502 , 0.1305864 , 0.15701319, 0.63458981, 0.10044303,
       0.07697613, 0.70545696, 0.81063873, 0.40993811, 0.4004089 ,
       0.8279108 , 0.86115947, 0.54743059, 0.7831907 , 0.39351282,
       0.90031813, 0.06604284, 0.68982515, 0.1711916 , 0.48457729,
       0.72892388, 0.47947618, 0.72708077, 0.76374847, 0.10289324,
       0.75976313, 0.12764982, 0.1270855 , 0.19282183, 0.96943587,
       0.6798997 , 0.58254125, 0.44127708, 0.109379  , 0.9158226 ,
       0.91782232, 0.00998366, 0.43903144, 0.15972028, 0.7058152 ,
       0.31672714, 0.03467287, 0.41767329, 0.46976989, 0.72005

In [4]:
sum(L)

50.38881093077363

In [5]:
np.sum(L)

50.38881093077363

In [6]:
np.min(L)

0.009983656807971641

In [7]:
np.max(L)

0.9801129544271407

In [9]:
x = np.arange(16).reshape(4, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.sum(x)

120

In [17]:
np.sum(x, axis = 0)

array([24, 28, 32, 36])

In [19]:
np.prod(x) ##元素相乘

0

In [20]:
np.mean(x) ##求平均值

7.5

In [21]:
np.median(x) ##求中位数

7.5

In [24]:
np.percentile(x, q = 50)

7.5

---
通过几个百分位点判断数据的形式

In [25]:
for percent in(0, 25, 50, 75, 100):
    print(np.percentile(x, q = percent))

0.0
3.75
7.5
11.25
15.0


---
利用random模块中normal方法构造平均值为0，标准差为1， 样本为1000000的数组

In [26]:
np.var(x)

21.25

In [27]:
np.std(x)

4.6097722286464435

In [28]:
x = np.random.normal(0, 1, size = 1000000)

In [29]:
np.mean(x)

0.0019067673929533168

In [30]:
np.std(x)

0.9994793511659779