# 索引
> **argmin(arguement)方法查看数组中最小值的位置**

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, size=10000000)

In [3]:
np.min(x)

-5.126514162186275

In [4]:
np.argmin(x)

8815686

In [6]:
x[8815686]

-5.126514162186275

In [9]:
np.argmax(x)

4422143

## 排序和使用索引
> **random模块中shuffle方法对数组乱序操作**

> **sort方法对数组排序操作,二维数组具有参数axis**

> **argsort方法返回的结果是原数组的索引值**

> **partition方法以某一个值为分界线划分，也支持argpartition返回索引值**

In [11]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
np.random.shuffle(x)
x

array([ 8,  7, 13, 12,  5,  3, 10,  6, 15,  1,  2,  9,  4,  0, 14, 11])

In [14]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
x = np.random.randint(10, size = (4,4))
x

array([[2, 6, 0, 4],
       [3, 4, 8, 0],
       [1, 0, 2, 4],
       [1, 8, 9, 4]])

In [22]:
np.sort(x)

array([[0, 2, 4, 6],
       [0, 3, 4, 8],
       [0, 1, 2, 4],
       [1, 4, 8, 9]])

In [24]:
np.sort(x, axis = 0)

array([[1, 0, 0, 0],
       [1, 4, 2, 4],
       [2, 6, 8, 4],
       [3, 8, 9, 4]])

In [26]:
np.argsort(x)

array([[2, 0, 3, 1],
       [3, 0, 1, 2],
       [1, 0, 2, 3],
       [0, 3, 1, 2]], dtype=int64)

In [30]:
np.partition(x,2,axis = 0)

array([[1, 0, 0, 0],
       [1, 4, 2, 4],
       [2, 6, 8, 4],
       [3, 8, 9, 4]])