## Fancy Indexing 
> **fancy indexing 是指在数组索引中传入数组或矩阵（代表的都是原数组的索引），形成新的数组或矩阵**

> **也可以传入布尔数组 , 只筛选真值为真的列数，<font color = red>非常重要,结合数组的比较。
</font>**

In [1]:
import numpy as np
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
index = [3, 5 ,8] ##想要得到数组索引值为3， 5， 8 的元素

In [3]:
x[index] ##直接传入index，得到新的数组

array([3, 5, 8])

In [4]:
ind = np.array([[0,2],[1,3]]) ## 传入二维矩阵，形成新的矩阵
x[ind]

array([[0, 2],
       [1, 3]])

---
<font color=red>数组元素查找的高级方法，利用传入数组或矩阵查找</font>

In [5]:
x = x.reshape(4, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
row = np.array([0, 1, 2]) ##对数据的行筛选
col = np.array([1, 2, 3]) ##对数据的列筛选

In [7]:
x[row, col]

array([ 1,  6, 11])

In [8]:
x[0, col]

array([1, 2, 3])

In [9]:
x[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

---
<font color=red>fancy indexing 也可以传入布尔数组,只筛选真值为真的行数</font>

In [10]:
col = [True, False, True, False]

In [11]:
x[1:3, col]

array([[ 4,  6],
       [ 8, 10]])

## numpy.array的比较(返回的是布尔数组)
> **直接用比较运算符，numpy中的数组返回的就是布尔类型数组**

> **调用np.sum方法或是count_nonzero方法，统计布尔数组真的个数**

> **any方法或是all方法查看是否满足条件，二维数组支持axis**

> **比较支持位运算& ~ |，而不是条件运算符&&，因为连接的不是两个条件**

In [14]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
( x % 2 == 0 ) & (x < 10)

array([ True, False,  True, False,  True, False,  True, False,  True,
       False, False, False, False, False, False, False])

In [22]:
2 * x == 24 - 4 *x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [24]:
X = x.reshape(4, -1)
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

---
调用sum方法和count_nonzero方法查看数组中真的元素

any方法判断是否有任意元素满足条件,all方法查看全部元素满足条件

In [25]:
np.sum(x <= 3)

4

In [26]:
np.count_nonzero(x <= 3)

4

In [27]:
np.any(x == 0)

True

In [28]:
np.all(x == 0)

False

In [30]:
np.sum(X % 2 ==0 ,axis = 1)

array([2, 2, 2, 2])

In [32]:
np.all(X > 0 , axis = 1)

array([False,  True,  True,  True])

In [33]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
np.sum((x>3)&(x<10))

6

In [35]:
np.sum(~(x == 0))

15

---
fancy indexing结合数组的比较<FONT COLOR=RED>注意fancy indexing的使用，对于二维矩阵，行索引应该为一维，且个数于矩阵行元素的个数相同，如果不同则会报错</font>

In [36]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [42]:
X[X[:,3] % 3 ==0 , :] ## 满足最后一列是3的倍数的行数

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [44]:
X[:3, X<5] ## X<5 返回的结构是一个二维数组，无法索引

IndexError: too many indices for array