## 数据归一化
> **解决方案：将所有的数据映射到同一尺度**

> **最值归一化（normalization）：把所有数据映射到0-1之间（将数据映射到xmax~xmin中）,适用于分布有明显边界的情况；受outlier影响较大。**

> **均值方差归一化（standardization）：把所有数据归一到均为0，方差为1的分布中。适用于数据没有明显的边界；有可能存在极端数据值**

<img src='./picture/7-1.png' style='width:500px;height:300px;float:middle'>

## 最值归一化 Normalization
> **调用array(dtype=float)强制类型转换**

<img src='./picture/7-2.png' style='width:300px;height:180px;float:middle'>

In [1]:
import numpy as np
x = np.random.randint(0, 100, size =100)

In [2]:
(x - np.min(x))/(np.max(x)-np.min(x)) ##是一个universal function，向量中的每个元素都减去一个值

array([0.36363636, 0.73737374, 0.32323232, 0.2020202 , 0.03030303,
       0.24242424, 0.96969697, 0.91919192, 0.66666667, 0.05050505,
       0.94949495, 0.67676768, 0.27272727, 0.67676768, 0.91919192,
       0.95959596, 0.93939394, 0.55555556, 0.05050505, 0.72727273,
       0.88888889, 0.43434343, 0.02020202, 0.81818182, 0.78787879,
       0.64646465, 0.48484848, 0.8989899 , 1.        , 0.66666667,
       0.86868687, 0.45454545, 0.49494949, 0.45454545, 0.26262626,
       0.86868687, 0.70707071, 0.92929293, 0.15151515, 0.75757576,
       0.24242424, 0.66666667, 0.04040404, 0.14141414, 0.05050505,
       0.41414141, 0.2020202 , 0.55555556, 0.87878788, 0.41414141,
       0.63636364, 1.        , 0.01010101, 0.23232323, 0.23232323,
       0.13131313, 0.28282828, 0.21212121, 0.71717172, 0.81818182,
       0.98989899, 0.60606061, 0.63636364, 0.39393939, 0.94949495,
       0.91919192, 0.85858586, 0.24242424, 0.91919192, 0.        ,
       0.04040404, 0.76767677, 0.26262626, 0.67676768, 0.54545

In [10]:
X = np.random.randint(0, 100, (50,2)) ##二维数组的最值归一化

In [4]:
X[:10 , :]

array([[73, 84],
       [63, 43],
       [ 0, 70],
       [64, 40],
       [ 6, 37],
       [42, 25],
       [ 7, 99],
       [72, 34],
       [33,  2],
       [38, 90]])

In [5]:
X = np.array(X, dtype=float) ##强制类型转换

In [6]:
X[:, 0] = (X[:,0]-np.min(X[:,0]))/(np.max(X[:, 0])-np.min(X[:,0]))

In [7]:
X[:, 1] = (X[:,1]-np.min(X[:,1]))/(np.max(X[:, 1])-np.min(X[:,1]))

In [8]:
X[:10, :]

array([[0.73737374, 0.84693878],
       [0.63636364, 0.42857143],
       [0.        , 0.70408163],
       [0.64646465, 0.39795918],
       [0.06060606, 0.36734694],
       [0.42424242, 0.24489796],
       [0.07070707, 1.        ],
       [0.72727273, 0.33673469],
       [0.33333333, 0.01020408],
       [0.38383838, 0.90816327]])

In [9]:
np.mean(X[:,0])

0.5018181818181818

## 均值方差归一化 Standardization

<img src='./picture/7-3.png' style='width:300px;height:180px;float:middle'>

In [11]:
X2 = np.random.randint(0, 100,(50,2))

In [13]:
X2 = np.array(X2, dtype=float)

In [14]:
X2[:,0] = (X2[:,0]-np.mean(X2[:,0]))/np.std(X2[:, 0])

In [15]:
X2[:,1] = (X2[:,1]-np.mean(X2[:,1]))/np.std(X2[:, 1])

In [16]:
X2[:10,:]

array([[ 0.83010409, -1.15585509],
       [-1.67765346,  0.28810427],
       [ 1.70236759, -1.12147511],
       [ 0.10321785, -0.43387541],
       [-0.76904565, -1.08709512],
       [-0.95076721, -0.02131559],
       [-1.67765346,  0.42562421],
       [ 0.46666097,  0.25372429],
       [-1.53227621, -0.81205524],
       [ 1.4479574 ,  1.14760389]])